---
permalink: performance-checker/concept_metrocluster_configuration_verification.html 
sidebar: sidebar 
keywords: metrocluster, configuration, verification 
summary: È possibile prevenire i problemi di performance per i carichi di lavoro mirrorati in una configurazione MetroCluster garantendo che la configurazione MetroCluster sia impostata correttamente. È inoltre possibile migliorare le performance dei carichi di lavoro modificando la configurazione o aggiornando i componenti software o hardware. 
---
= Verifica della configurazione MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È possibile evitare problemi di performance per i carichi di lavoro mirrorati in configurazioni MetroCluster su FC e IP, garantendo che la configurazione MetroCluster sia configurata correttamente. È inoltre possibile migliorare le performance dei carichi di lavoro modificando la configurazione o aggiornando i componenti software o hardware.

Fare riferimento alla https://docs.netapp.com/us-en/ontap-metrocluster/index.html["Documentazione MetroCluster"] per le istruzioni sulla configurazione dei cluster nella configurazione MetroCluster, inclusi switch Fibre Channel (FC), cavi e collegamenti interswitch (ISL). Inoltre, consente di configurare il software MetroCluster in modo che i cluster locali e remoti possano comunicare con i dati del volume mirror. Per informazioni specifiche sulla configurazione di MetroCluster over IP, consultare https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/index.html["Installare una configurazione IP MetroCluster"].

Puoi confrontare la tua configurazione di MetroCluster con i requisiti in https://docs.netapp.com/us-en/ontap-metrocluster/index.html["Documentazione MetroCluster"] per determinare se la modifica o l'upgrade dei componenti nella tua configurazione MetroCluster potrebbe migliorare le performance del carico di lavoro. Questo confronto può aiutarti a rispondere alle seguenti domande:

* I controller sono appropriati per i carichi di lavoro?
* Hai bisogno di aggiornare i bundle ISL a una larghezza di banda più ampia per gestire un throughput maggiore?
* È possibile regolare i crediti buffer-to-buffer (BBC) sugli switch per aumentare la larghezza di banda?
* Se i tuoi carichi di lavoro hanno un elevato throughput di scrittura su storage SSD (Solid state Drive), devi aggiornare i bridge FC-SAS per adattarli al throughput?


*Informazioni correlate*

* Per informazioni sulla sostituzione o l'aggiornamento dei componenti di MetroCluster, vedere https://docs.netapp.com/us-en/ontap-metrocluster/index.html["Documentazione MetroCluster"] .
* Per informazioni sull'aggiornamento dei controller, vedere https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_controllers_in_a_four_node_fc_mcc_us_switchover_and_switchback_mcc_fc_4n_cu.html["Aggiornamento dei controller in una configurazione FC MetroCluster tramite switchover e switchback"] e. https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/task_upgrade_controllers_in_a_four_node_ip_mcc_us_switchover_and_switchback_mcc_ip.html["Aggiornamento dei controller in una configurazione IP MetroCluster tramite switchover e switchback"]

