---
permalink: install-vapp/task_download_unified_manager_ova_file.html 
sidebar: sidebar 
keywords: download, unified manager, installation, file 
summary: Scarica il file di installazione di Unified Manager dal sito di supporto NetApp per implementare Unified Manager come appliance virtuale. 
---
= Download del file di installazione di Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Scarica il file di installazione di Unified Manager dal sito di supporto NetApp per implementare Unified Manager come appliance virtuale.

*Cosa ti serve*

È necessario disporre delle credenziali di accesso per il NetApp Support Site.

Il file di installazione è un `.tar` file contenente un certificato root, un `README` file e un `OVA` software Unified Manager configurato per un'appliance virtuale.

.Fasi
. Accedere al NetApp Support Site e accedere alla pagina Download di Unified Manager:
+
https://mysupport.netapp.com/site/products/all/details/activeiq-unified-manager/downloads-tab["Sito di supporto NetApp"]

. Selezionare la versione richiesta di Unified Manager e accettare il contratto di licenza con l'utente finale (EULA).
. Scaricare e salvare il `.tar` file per l'installazione di VMware vSphere in una directory locale o di rete accessibile al client vSphere.
. Verificare il checksum per assicurarsi che il software sia stato scaricato correttamente.
. Passare alla directory in cui è stato scaricato il `.tar` file e immettere il seguente comando nella finestra del terminale per espandere il pacchetto di Unified Manager:
+
[listing]
----
tar -xvzf ActiveIQUnifiedManager-<version>.tar.gz
----
+
Il file richiesto `OVA`, un certificato di origine e un `README` file per Unified Manager vengono decompressi nella directory di destinazione.

. Verificare l'integrità del `OVA` file attenendosi alla procedura fornita nel `README` file.

